name: CI release

on:
  schedule:
  # Cron uses UTC time
  - cron: 0 21 * * 0 # Runs at 21:00 UTC every Sunday
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - name: Create release
         run: |
           export TAG="$(( $(date +"%U") - 5))"
           gh release list > /tmp/list
           cat /tmp/list
           export SUB="$(grep -c "v0.${TAG}" /tmp/list)"
           echo "v0.${TAG}.${SUB}"
           gh release create "v0.${TAG}.${SUB}" --generate-notes --target release
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
