# .github/workflows/convert-to-pdf.yml

name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'report/**.md'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: report
          output_dir: report-gen
          # Default is true, can set to false to only get PDF files
          build_html: false
      - run: mkdir -p report/build/
      - run: cp report-gen/Report.pdf report/build/Report.pdf
      - run: git add report/Report.pdf
      - run: git config user.email "gha@gha.gha"
      - run: git config --global user.name "GHA PDF workflow"
      - run: git commit -m"Update PDF"
      - run: git push
